import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

import { useState } from "react";

import Navi from "../components/Navi";
import Hero from "../components/Hero";
import Skills from "../components/Skills";
import Portfolio from "../components/Portfolio";
import Games from "../components/Games";
import Contact from "../components/Contact";
import Nav from "../components/Nav";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Claire Lee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="bg-gray-900 w-full-screen h-full-screen">
        <section className="min-h-screen w-full-screen">
          <Hero />
        </section>
        <section className="bg-gray-900 w-full-screen h-full-screen">
          <Skills />
        </section>
        <section className="bg-gray-900 w-full-screen h-full-screen">
          <Portfolio />
        </section>
        <section className="bg-gray-900 w-full-screen h-full-screen">
          <Games />
        </section>
        <section className="bg-gray-900 w-full-screen h-full-screen">
          <Contact />
        </section>
      </main>
    </div>
  );
}
