import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";

import { useState } from "react";

import Navi from "../components/Navi";
import Hero from "../components/Hero";
import Skills from "../components/Skills";
import Portfolio from "../components/Portfolio";
import Games from "../components/Games";
import Contact from "../components/Contact";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Claire Lee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navi mode={darkMode} setDarkMode={setDarkMode} />
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <Hero />
        </section>
        <section>
          <Skills />
        </section>
        <Portfolio />
        <Games />
        <Contact />
      </main>
    </div>
  );
}
